[2024-10-04T00:36:51.176+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T00:36:51.229+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: smiles_to_s3.save_to_s3 scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T00:36:51.235+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: smiles_to_s3.save_to_s3 scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T00:36:51.235+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-10-04T00:36:51.245+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): save_to_s3> on 2024-10-03 00:00:00+00:00
[2024-10-04T00:36:51.253+0000] {standard_task_runner.py:57} INFO - Started process 1615 to run task
[2024-10-04T00:36:51.257+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'smiles_to_s3', 'save_to_s3', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdk1hnx7q']
[2024-10-04T00:36:51.259+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask save_to_s3
[2024-10-04T00:36:51.278+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T00:36:51.323+0000] {task_command.py:410} INFO - Running <TaskInstance: smiles_to_s3.save_to_s3 scheduled__2024-10-03T00:00:00+00:00 [running]> on host 67f55c40a956
[2024-10-04T00:36:51.333+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T00:36:51.405+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='smiles_to_s3' AIRFLOW_CTX_TASK_ID='save_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T00:36:52.594+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 83, in save_to_s3
    s3_client.put_object(Bucket=S3_BUCKET, Key=f"smiles_data_{datetime.now().date()}.xlsx", Body=output.getvalue())
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (RequestTimeTooSkewed) when calling the PutObject operation: The difference between the request time and the current time is too large.
[2024-10-04T00:36:52.604+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=smiles_to_s3, task_id=save_to_s3, execution_date=20241003T000000, start_date=20241004T003651, end_date=20241004T003652
[2024-10-04T00:36:52.614+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 41 for task save_to_s3 (An error occurred (RequestTimeTooSkewed) when calling the PutObject operation: The difference between the request time and the current time is too large.; 1615)
[2024-10-04T00:36:52.624+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-10-04T00:36:52.654+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
